# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

## Login

POST {{host}}/login
Accept-Language: ru
Accept: application/json
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    client.global.set('bearerToken', response.body.access_token);
    client.global.set('refreshToken', response.body.refresh_token);
 %}

### Get user

GET {{host}}/user
Accept: application/json
Authorization: Bearer {{bearerToken}}

### Logout

POST {{host}}/logout
Accept: application/json
Authorization: Bearer {{bearerToken}}

### Get organizations

GET {{host}}/organisation?filter=trial
Accept: application/json
Authorization: Bearer {{bearerToken}}

### Get organizations

POST {{host}}/organisation
Accept: application/json
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "name": "New organization 1"
}

###
